Added debugging folder/dll to gadgets
gadgetron/gadgetron pull request #1089
Opened 2022-04-13 16:27 UTC by apd47

As mentioned in #1087, this PR moves some of the untested "debugging-type" gadgets into their own subdirectory of "gadgets", and into their own DLL. These gadgets are mostly untested, and shouldn't be used in production pipelines - but rather for debugging purposes by developers/advanced users.

2022-04-13 17:34 UTC, apd47 commented
The tests are failing on the ismrmrd_dump_gadget_test.cfg run, but I'm not sure why. That test uses a different format, where instead of a configuration being set, a "template" is used instead:
template=ismrmrd_dump_gadget_test.template.xml

The XML file it specifies doesn't seem to exist either - does anyone happen to know how this test works so I can chase down the failure?

2022-04-15 16:00 UTC, apd47 commented
@hansenms - looks like moving the dump gadget back into mri_core (where it should be) means test pass - I'll still take a look at the template method setup for next time, but I think we're set on this one whenever you get a chance.

2022-04-15 16:15 UTC, hansenms commented on gadgets/mri_core/CMakeLists.txt
> +    	  cpuisa.h
nit: extra space here

2022-04-15 16:20 UTC, hansenms commented
I think we need to validate if any of these gadgets are used in any chains and update those. See for example: https://github.com/gadgetron/gadgetron/blob/master/gadgets/python/legacy/config/pseudoreplica.xml

2022-04-15 16:23 UTC, apd47 commented
Oh - good catch. I'd checked tests but not all the untested configs. Working through now.

2022-04-15 16:32 UTC, apd47 commented
My search through all the configs looks like Pseudoreplica.xml was the only one using any of these 6 gadgets, so that's been updated. Also fixed the extra space in cmakelists

2022-04-15 16:33 UTC, apd47 commented
(accidental close - tabbed to the wrong button...)

2022-04-15 16:34 UTC, apd47 commented
/azp run

2022-04-15 23:35 UTC, hansenms requested changes
Can we bump the patch version at least just to make it clear that things are moving around.

2022-04-15 23:57 UTC, apd47 commented
Sounds like a good idea - I'm not sure how to do that, actually

2022-04-18 15:44 UTC, hansenms commented
@apd47 version numbers are in the main CMakeLists.txt file.

2022-04-18 20:09 UTC, hansenms approved these changes

2022-04-18 21:00 UTC, merged