Windows fix
gadgetron/gadgetron pull request #930
Opened 2021-02-23 07:43 UTC by dchansen

This pull request fixes compilation on Windows. It passes all integration tests, including CUDA, python and matlab.
The pseudoreplica test was removed, as the test cases turned out to be extremely fragile  and the dependent on the exact random number generator used. The implementation itself is also of limited utility, and should probably be removed entirely.

2021-02-23 18:36 UTC, hansenms commented
I am unable to get this to compile on my Windows machine. Here are some notes on how I installed:

1. I have Visual Studio 2019. Version 16.8.6. (Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29337 for x86)
2. I have Intel oneAPI version 2021.1.1
3. I have CUDA v11.2/142 (Cuda compilation tools, release 11.2, V11.2.142)
4. CMake 3.20.0-rc1

I install dependencies with:

```powershell
vcpkg install boost fftw3 armadillo plplot pugixml openblas ismrmrd python3 hdf5 range-v3 libxml2 libxslt dcmtk gtest
```

I ran `vcpkg` for a few other things, so here is my list pf packages:

```
armadillo:x64-windows                              10.2.0           Armadillo is a high quality linear algebra libra...
blas:x64-windows                                   1                Metapackage for packages which provide BLAS
boost-accumulators:x64-windows                     1.75.0           Boost accumulators module
boost-algorithm:x64-windows                        1.75.0           Boost algorithm module
boost-align:x64-windows                            1.75.0           Boost align module
boost-any:x64-windows                              1.75.0           Boost any module
boost-array:x64-windows                            1.75.0           Boost array module
boost-asio:x64-windows                             1.75.0#1         Boost asio module
boost-assert:x64-windows                           1.75.0           Boost assert module
boost-assign:x64-windows                           1.75.0           Boost assign module
boost-atomic:x64-windows                           1.75.0           Boost atomic module
boost-beast:x64-windows                            1.75.0           Boost beast module
boost-bimap:x64-windows                            1.75.0           Boost bimap module
boost-bind:x64-windows                             1.75.0           Boost bind module
boost-build:x64-windows                            1.75.0.beta1#1   Boost.Build
boost-callable-traits:x64-windows                  1.75.0           Boost callable_traits module
boost-chrono:x64-windows                           1.75.0           Boost chrono module
boost-circular-buffer:x64-windows                  1.75.0           Boost circular_buffer module
boost-compatibility:x64-windows                    1.75.0           Boost compatibility module
boost-compute:x64-windows                          1.75.0           Boost compute module
boost-concept-check:x64-windows                    1.75.0#1         Boost concept_check module
boost-config:x64-windows                           1.75.0           Boost config module
boost-container-hash:x64-windows                   1.75.0           Boost container_hash module
boost-container:x64-windows                        1.75.0           Boost container module
boost-context:x64-windows                          1.75.0           Boost context module
boost-contract:x64-windows                         1.75.0           Boost contract module
boost-conversion:x64-windows                       1.75.0           Boost conversion module
boost-convert:x64-windows                          1.75.0           Boost convert module
boost-core:x64-windows                             1.75.0           Boost core module
boost-coroutine2:x64-windows                       1.75.0           Boost coroutine2 module
boost-coroutine:x64-windows                        1.75.0           Boost coroutine module
boost-crc:x64-windows                              1.75.0           Boost crc module
boost-date-time:x64-windows                        1.75.0           Boost date_time module
boost-detail:x64-windows                           1.75.0           Boost detail module
boost-dll:x64-windows                              1.75.0           Boost dll module
boost-dynamic-bitset:x64-windows                   1.75.0           Boost dynamic_bitset module
boost-endian:x64-windows                           1.75.0           Boost endian module
boost-exception:x64-windows                        1.75.0           Boost exception module
boost-fiber:x64-windows                            1.75.0           Boost fiber module
boost-filesystem:x64-windows                       1.75.0           Boost filesystem module
boost-flyweight:x64-windows                        1.75.0           Boost flyweight module
boost-foreach:x64-windows                          1.75.0           Boost foreach module
boost-format:x64-windows                           1.75.0           Boost format module
boost-function-types:x64-windows                   1.75.0           Boost function_types module
boost-function:x64-windows                         1.75.0           Boost function module
boost-functional:x64-windows                       1.75.0           Boost functional module
boost-fusion:x64-windows                           1.75.0           Boost fusion module
boost-geometry:x64-windows                         1.75.0           Boost geometry module
boost-gil:x64-windows                              1.75.0           Boost gil module
boost-graph-parallel:x64-windows                   1.75.0           Boost graph_parallel module
boost-graph:x64-windows                            1.75.0           Boost graph module
boost-hana:x64-windows                             1.75.0           Boost hana module
boost-heap:x64-windows                             1.75.0           Boost heap module
boost-histogram:x64-windows                        1.75.0           Boost histogram module
boost-hof:x64-windows                              1.75.0           Boost hof module
boost-icl:x64-windows                              1.75.0           Boost icl module
boost-integer:x64-windows                          1.75.0           Boost integer module
boost-interprocess:x64-windows                     1.75.0           Boost interprocess module
boost-interval:x64-windows                         1.75.0           Boost interval module
boost-intrusive:x64-windows                        1.75.0           Boost intrusive module
boost-io:x64-windows                               1.75.0           Boost io module
boost-iostreams:x64-windows                        1.75.0           Boost iostreams module
boost-iterator:x64-windows                         1.75.0           Boost iterator module
boost-json:x64-windows                             1.75.0           Boost json module
boost-lambda:x64-windows                           1.75.0           Boost lambda module
boost-leaf:x64-windows                             1.75.0           Boost leaf module
boost-lexical-cast:x64-windows                     1.75.0           Boost lexical_cast module
boost-local-function:x64-windows                   1.75.0           Boost local_function module
boost-locale:x64-windows                           1.75.0           Boost locale module
boost-lockfree:x64-windows                         1.75.0           Boost lockfree module
boost-log:x64-windows                              1.75.0           Boost log module
boost-logic:x64-windows                            1.75.0           Boost logic module
boost-math:x64-windows                             1.75.0           Boost math module
boost-metaparse:x64-windows                        1.75.0           Boost metaparse module
boost-modular-build-helper:x64-windows             1.75.0#5
boost-move:x64-windows                             1.75.0           Boost move module
boost-mp11:x64-windows                             1.75.0           Boost mp11 module
boost-mpl:x64-windows                              1.75.0           Boost mpl module
boost-msm:x64-windows                              1.75.0           Boost msm module
boost-multi-array:x64-windows                      1.75.0           Boost multi_array module
boost-multi-index:x64-windows                      1.75.0           Boost multi_index module
boost-multiprecision:x64-windows                   1.75.0           Boost multiprecision module
boost-nowide:x64-windows                           1.75.0  [...]

2021-02-25 18:41 UTC, hansenms requested changes
It is a bit tough to review this since it does a few different things:
1. Stuff specifically to get Windows building
2. Switched to boost::asio for python
2. Adding some unit tests
3. Removed an integration test (pseudo replica)
4. Some white space/formatting changes. 
5. Adds some debug statements.

Not totally clear what is needed for Windows build and what is other "stuff" needed for other things. It is probably mostly fine, but it would be good to know why this removes an integration test? Was that intentional?

2021-02-25 19:17 UTC, dchansen commented
Absolutely intentional. The integration test was essentially checking the 32 bit mersenne twister in GCC, and nothing else. 
If ANYTHING about the random number generation was changed (including moving to a different standard library such as MSVC, or boost) the test would fail. 
I could have rewritten the Gadget to use Boost random and updated the test files, but fact is the entire chain is broken and has never worked. We can't remove it yet, because it would be an API break, but we should with the next major release.
If someone wants to implement pseudoreplica properly, that would be cool, but right now it should just be removed.

As for the other changes, there aren't really any that are not related to windows. The python discovery for instance is needed to make the python tests work on windows.

2021-02-26 21:55 UTC, hansenms approved these changes
I am unable to compile with Python support on my Windows machine. It finds Python library (installed with vcpkg), but then fails to find the python executable. I think the issue is that vcpkg doesn't install an executable, so it relies on a python distro on the machine. Not sure if this is something to resolve in this PR, but it will prevent us from having build automation working properly if we have some gnarly Python setup to configure on the side. 

I also had to hack the FindMKL.cmake script for Intel oneAPI. I think we should open an issue to fix that since that is the only way to download MKL for now.

I am OK with merging this for now, but we still have a little ways to go for a nice build experience on Windows.

2021-02-27 20:34 UTC, dchansen commented
You're right. I'm not compiling with Python support either. The python package in vcpkg is somewhat useless for our purposes, and we should drop it from the install list. 
This is different than being able to run python gadgets however!

The compiled python support is only for calling python from within a c++ gadget, and nothing else. It is not used in any integration test, but in a few unit tests. I believe there is quite a bit of user code relying on this feature, so we can't drop it entirely.

Running the python gadgets only requires "python" or "python3" to be on the path and be a valid python 3.5+ distribution with the gadgetron-python package installed. I'm using Anaconda on windows, but I think we could even get away with python from the windows store.

2021-02-27 20:34 UTC, merged